### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by UncleDozer** [0rax/fishline#2]
It seems that I don't have any of the fonts for the symbol (ie: the write lock symbol etc) and I was just wondering which font you were using for those. Thanks for this by the way, works great.

**Comment by 0rax** [comment]
Hi, you can use any patched fonts from Powerline, you might want to check this repository https://github.com/powerline/fonts for already patched fonts or patch it yourself.

I am currently using the Terminus one, this is the one shown in the screenshot on the front page of the repository.

Thanks for checking out this project.

**Comment by UncleDozer** [comment]
I thought that looked like Terminus. Thanks for the link, I'm patching the Terminus now.
