### ISSUE TITLE
duplicate entries added to $fish_function_path, resulting in no function loading

### ISSUE THREAD

**Issue by drewcassidy** [0rax/fishline#30]
the current init.fish causes duplicate entries to be added to $fish_function_path when running nested fish instances or if the config.fish file doesnt have guards against running in non-interactive mode. This causes functions not to autoload on linux (works fine in macOS). While this is probably also a bug in fish, it should probably be fixed here to avoid cluttering environment variables

**Comment by drewcassidy** [comment]
Turns out the issue I was running into was [#5348](https://github.com/fish-shell/fish-shell/issues/5348), and the fix is related, fish_function_path shouldn't be exported as an environment variable

**Comment by 0rax** [comment]
Closed by #31
