### ISSUE TITLE
Unable to install the plugin using fisher v4.3.1

### ISSUE THREAD

**Issue by gsshiva** [0rax/fishline#36]
The Project documentation says the following to install using fisher

> fisher add 0rax/fishline

but on `fisher` version 4.3,  there is no such option as `add` and only `install`. The following commands only brings in just `fishline.fish`and nothig else. 
```
% fisher -v
fisher, version 4.3.1

% fisher install 0rax/fishline
fisher install version 4.3.1
In config.fish /home/GSS
Fetching https://codeload.github.com/0rax/fishline/tar.gz/HEAD
Installing 0rax/fishline
           /home/shiva/.config/fish/functions/fishline.fish
Installed 1 plugin/s
```

Creating a fish prompt as below
```fish
function fish_prompt
    fishline -s $status
end
```
results in the following 
```
__fishline_segment_close: command not found
~/.config/fish/functions/fishline.fish (line 71): 
    __fishline_segment_close
    ^
in function 'fishline' with arguments '-s 0'
	called on line 2 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
```
Let me know what I am missing. Thanks for your work.

**Comment by 0rax** [comment]
Thanks for your report, I do not personally use `fisher` in part due to how the API tends not to be that much stable.

I will look into it right now trying to figure out how can I make the package install correctly once again.

**Comment by 0rax** [comment]
Another issue exist to report incompatibility with fisher >=4, I will close this issue as duplicate and continue tracking this issue in #33.
